### ISSUE TITLE
Provide central logfile/ email alert to Jisc staff, when data has been uploaded/ validated by users or institutions (usage report?)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#11]
This would be useful - but low priority... could maybe be used for an organisation to submit a successfully validated dataset to us, into another folder/ holding area? TBD

**Comment by huwrobertsjisc** [comment]
Working on... Watch this space.

**Comment by huwrobertsjisc** [comment]
Administrators can now view all reports and all exports for all users and can download all too.
