### ISSUE TITLE
Back end: Need ability to handle files of the wrong name without crashing

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/udd-web-validator#14]
As per title

**Comment by robwynj** [comment]
I think you need the option to select a file of any name against that entity (individual file per entity option) or the bulk upload (based on standard filename convention, as per UDD github guidance). Worth offering both options maybe?

**Comment by huwrobertsjisc** [comment]
No - we have file name conventions on GitHub. See here:
https://github.com/jiscdev/analytics-udd/blob/master/filename_conventions.md
