### ISSUE TITLE
Need ability to cache Validation progress / information screen

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#17]
I log out or refresh the browser (or I even lose my network connection), and the current progress of the validation disappears, and I have to re-start the validation process again to capture that information - would be useful if that screen is cached, and can then be cleared upon new validation run?

**Comment by huwrobertsjisc** [comment]
Added "My Last Validation Request" page allowing a user to view their last validation request.

**Comment by huwrobertsjisc** [comment]
Fixed in this evening's UAT release.
