### ISSUE TITLE
Conversion Tools - TSV to JSON issue (probably affects TSV to XML conversion too)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#19]
Found issue in converting TSV files which have trailing / multiple tabs within, which gives output (JSON) as follows:

{"MOD_ID":"AM10CP^1","MOD_NAME":"Mathematical Algorithms","MOD_SUBJECT":"G140","MOD_CREDITS":"10","MOD_LEVEL":"1","CREDIT_BEARING":"1","":null,"":null,"":null,"":null}

So we have multiple (4) NULL entries with empty JSON keys for each one. This is because we have multiple tabs provided in the actual source TSV file provided in this case, after the final JSON key provided (in this example, CREDIT_BEARING field).

**Comment by huwrobertsjisc** [comment]
It will be the same for both TSV to XML and TSV to JSON. Fixed in development.
Will be released into UAT on Monday 10th April.

**Comment by huwrobertsjisc** [comment]
Released into UAT
