### ISSUE TITLE
Need ability to export all reports as a ZIPped file

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/udd-web-validator#2]
Currently it's possible to download a validation report, a referential integrity report and a data quality report on a per entity basis. 

It would be good to be able to download all validation reports for a given session in 1 go. Same goes for referential integrity and data quality reports.

**Comment by robwynj** [comment]
Can this be done to cater for one single ZIP file/ pack of files too, not just 3 individual (validation, quality, referential check report) packs.

**Comment by huwrobertsjisc** [comment]
No because some of the files are too big and take too long to produce.
