### ISSUE TITLE
Release Updates screen wanted inside the application

### ISSUE THREAD

**Issue by huwrobertsjisc** [jiscdev/udd-web-validator#51]
There's a need to create a release updates screen to show what's gone in the latest release and when the next release is planned.

**Comment by huwrobertsjisc** [comment]
Fixed in development. Waiting to be released into UAT.

**Comment by robwynj** [comment]
Hia,

Can we email all users to alert them of this (and allow them to select - via their profile in the web validator - to receive an email update of releases or updates going out in future) optionally.

Many Thanks

Rob

**Comment by huwrobertsjisc** [comment]
The man with the vision is the man for the job!

**Comment by huwrobertsjisc** [comment]
Released into UAT on Thursday 25th of May 2017.
