### ISSUE TITLE
Validation (1.3.0) around COURSEINSTANCE.ACADEMIC_YEAR, MODULEINSTANCE.MOD_ACADEMIC_YEAR

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#61]
courseinstance.academic_year is correct being a string in UDD 1.3.0, but was INT in 1.2.7 - one institution has experienced issues passing validation on this field - suspected this affects moduleinstance too. LRW API has experienced issues here too, around the "type" coming in.

**Comment by huwrobertsjisc** [comment]
This is a problem in the definition of the fields in the UDD. There is nothing to do on our side for this.

**Comment by huwrobertsjisc** [comment]
The UDD spec here was reverted back such that the academic year is expressed as an integer and not a string.
