### ISSUE TITLE
UDD Validator - Check of Institution JSON file first? Improvement Suggestion (FD#211)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#69]
Because my account has multiple options, and the session isn't maintained. I incorrectly uploaded Aston's data against the Abertay in the validator. This validated fine. I think as part of the validation process the UKPRN in the Institution entity should be validated against first. We do this on our side before any data is processed into Student Insight.  

This may cause issues with the current workflow as you will always need an institution file to be present, but it could prevent a significant problem occurring if this is not noticed an incorrect file shared with another institution.  Admittedly this issue won't impact Institutions using this but it could protect those of us who are doing this for multiple sites.

**Comment by huwrobertsjisc** [comment]
There is no concept at the moment of sharing between institutions. The only people who can see what others have done are administrators i.e. yourself, Gemma and myself. The only users who have access to multiple institutions are Tribal. 

I can look into this, but I would argue this is more of a training thing than anything else. If a set of validation reports have been created in error, there is scope to delete those files now.

**Comment by huwrobertsjisc** [comment]
Fixed in development on the 13th of July.

**Comment by huwrobertsjisc** [comment]
![image](https://user-images.githubusercontent.com/22907640/28224123-ce3e1b16-68c5-11e7-934a-f2cda99c1ba7.png)

**Comment by huwrobertsjisc** [comment]
Released into UAT on the 20th of July as planned.
