### ISSUE TITLE
Freeze upon Referential Integrity Checks - MODULEVLEMAP (command-line observed)

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#7]
Affects Cardiff Met Historical and Greenwich Live UDD datasets as at 3rd March 2017. Can't check on the web-validator, must affect it as observed the hang of command-line version.

**Comment by huwrobertsjisc** [comment]
Fixed in this evening's release into UAT. If the report takes more than 3 minutes to run, for whatever reason, it is abandoned. We cannot have the report tying up resources.
