### ISSUE TITLE
Ignore blank lines in TSV entity files used for validation

### ISSUE THREAD

**Issue by robwynj** [jiscdev/udd-web-validator#97]
Can we test to see if these are ignored during validation?

Kind Regards, Rob

**Comment by huwrobertsjisc** [comment]
We can test yes. Do you have a sample file that I can have?

**Comment by huwrobertsjisc** [comment]
Fixed in development. Expected to go into UAT on Thursday 16th of November 2017.

**Comment by huwrobertsjisc** [comment]
Released into UAT on Friday 17th of November.
